function [ out ] = ambi_make_description_string(S,C,suffix,separator)
    %UNTITLED2 Summary of this function goes here
    %   Detailed explanation goes here
    
    out = ...
        sprintf('%s%s%d%s%d%s',...
        S.name, separator, ...
        C.h_order, C.scheme(1), ...
        C.v_order, C.scheme(2), separator,...
        suffix);
end

