function [ output_args ] = run_dec_oal_2( )
   %UNTITLED Summary of this function goes here
   %   Detailed explanation goes here

   r = 2;

   [fl_x, fl_y, fl_z] = sph2cart(-30*pi/180, 0, r);
   
   S = ambi_spkr_array(...
       ... % array name
       'itu50', ...
       ... % coordinate codes, unit codes
       ... % Azimuth, Elevation, Radius; Degrees, Degrees, Meters
       'AER', 'DDM', ...
       ... % speaker name, [azimuth, elevation, radius]
       'BL', [ 110, 0, r], ...
       'FL', [  30, 0, r], ...
       'FC', [   0, 0, fl_x], ...
       'FR', [ -30, 0, r], ...
       'BR', [-110, 0, r] ...
       );
   
   ambi_run_allrad(S, [2,0], [0,0,1; 0,0,-1]);
end
