function [ output_args ] = run_dec_71x(num_top)
    % example specifying speaker locations inline
    % see also AMBI_SPKR_ARRAY, AMBI_MAT2SPKR_ARRAY, AMBI_RUN_ALLRAD
    
    %% decoder specs
    % decoder_type = 'pinv'; %'allrad'; % pinv | allrad
        
    % mixed_order_scheme = 'HV';
    
    %% speaker array definition
	
    % array_name=strcat('71',int2str(num_top));
	
	h_order_range = 1:3; %1:2;
    v_order_range = 1:3; %1:min(h_order,2);
	
    % radius
    r = 6;    % feet
    
    h_ele = 45; % deg
    hz = r * tan( h_ele * pi/180 );
	% hz=h_ele;
	z = 0;
	
    switch num_top
		case 2
			S = ambi_spkr_array(...
			... % array name
			'712', ...
			... % coordindate codes, unit codes
			'ARZ', 'DMM', ...
			... % speaker name, [azimuth, radius, elevation]
			... % 'Ear Level'
			'L',  [  30, r, z ], ...
			'R',  [ -30, r, z ], ...
			'C', [0, r, z ], ...
			'BL', [ 150, r, z ], ...				
			'BR', [-150, r, z ], ...
			'SL', [ 90, r, z ], ...
			'SR', [-90, r, z ], ...
			...
			'HSL', [ 90, r,  hz ], ...
			'HSR', [-90, r,  hz ] ...
			...
			);
		
        case 4
			S = ambi_spkr_array(...
			... % array name
			'714', ...
			... % coordindate codes, unit codes
			'ARZ', 'DMM', ...
			... % speaker name, [azimuth, radius, elevation]
			... % 'Ear Level'
			'L',  [  30, r, z ], ...
			'R',  [ -30, r, z ], ...
			'C', [0, r, z ], ...
			'BL', [ 150, r, z ], ...				
			'BR', [-150, r, z ], ...
			'SL', [ 90, r, z ], ...
			'SR', [-90, r, z ], ...
			...
			'HL',  [  45, r, hz ], ...
			'HR',  [ -45, r, hz ], ...
			'HBL', [ 135, r, hz ], ...				
			'HBR', [-135, r, hz ] ...

			...
			);		end


	for h_order = h_order_range
        for v_order = v_order_range
			ambi_run_allrad(S, [h_order,v_order], [0,0,-1]);
			ambi_run_pinv(S, [h_order,v_order], []);
		end
	end
    
end

