function run_dec_SAT25_v1
    % example specifying speaker locations inline
    %
    % see also AMBI_SPKR_ARRAY, AMBI_MAT2SPKR_ARRAY, AMBI_RUN_ALLRAD

    %% decoder specs
    decoder_type = 'allrad'; % pinv | allrad

    h_order_range = 1:3;
    v_order_range = 0:3;

    mixed_order_scheme = 'HP';

    %% speaker array definition
    % azimuth of speaker at front,
    % change to -45/2 for L/R config
    a0 = 0;
    az = (0:45:315) + a0

    % radius
    r = 6;    % feet

    % elevations
    el = [56+2/3, 23+1/3, -10] % degrees


    S = ambi_spkr_array(...
        ... % array name
        'SAT25', ...
        ... % coordindate codes, unit codes
        'ARE', 'DFD', ...
        ... % speaker name, [azimuth, radius, elevation]
        ... %
        ... % Top
        'T1', [     0, r,    90 ], ...
        ... % Imaginary
        ... % 'I1', [     0, 10,   -90 ] ...
        ... % Upper Ring
        'U1', [ az(1), r, el(1) ], ...
        'U2', [ az(2), r, el(1) ], ...
        'U3', [ az(3), r, el(1) ], ...
        'U4', [ az(4), r, el(1) ], ...
        'U5', [ az(5), r, el(1) ], ...
        'U6', [ az(6), r, el(1) ], ...
        'U7', [ az(7), r, el(1) ], ...
        'U8', [ az(8), r, el(1) ], ...
        ... % Middle Ring
        'M1', [ az(1), r, el(2) ], ...
        'M2', [ az(2), r, el(2) ], ...
        'M3', [ az(3), r, el(2) ], ...
        'M4', [ az(4), r, el(2) ], ...
        'M5', [ az(5), r, el(2) ], ...
        'M6', [ az(6), r, el(2) ], ...
        'M7', [ az(7), r, el(2) ], ...
        'M8', [ az(8), r, el(2) ], ...
        ... % Lower Ring
        'L1', [ az(1), r, el(3) ], ...
        'L2', [ az(2), r, el(3) ], ...
        'L3', [ az(3), r, el(3) ], ...
        'L4', [ az(4), r, el(3) ], ...
        ... %'L5', [ az(5), r, el(3) ], ...
        'L6', [ az(6), r, el(3) ], ...
        'L7', [ az(7), r, el(3) ], ...
        'L8', [ az(8), r, el(3) ] ...
        );


    %% do it
    for h_order = h_order_range
        for v_order = v_order_range
            if v_order <= h_order
                switch decoder_type
                    case 'allrad'
                        ambi_run_allrad(...
                            S, ...    % speaker array struct
                            [h_order,v_order], ...  % ambisonic order [h, v]
                            [0 0 -2], ... % imaginary speakers
                            [], ...   % pathname for output, [] = default
                            false, ... % do plots, default is true for MATLAB, false for Octave
                            mixed_order_scheme ... % mixed order scheme HV or HP
                            );
                    case 'pinv'
                        ambi_run_pinv(...
                            S, ...  % speaker array struct
                            [h_order,v_order], ...  % ambisonic order [h, v]
                            [], ... % imaginary speakers, none in this case
                            [], ... % pathname for output, [] = default
                            true, ... % do plots, default is true for MATLAB, false for Octave
                            mixed_order_scheme ... % mixed order scheme HV or HP
                            );
                end
            end
        end
    end

end

