function [ output_args ] = run_dec_itu( n_spkrs, radius)
    %UNTITLED Summary of this function goes here
    %   Detailed explanation goes here
    
    %% fill in default arguments
    if ~exist('radius', 'var') || isempty(radius)
        radius = 2;  % in meters!!
    end
    
    if ~exist('n_spkrs', 'var') || isempty(n_spkrs)
        n_spkrs = 5;
    end
    
    
    % distance to center speaker, assuming it is in the
    %  plane as the left and right.
    
    [fl_x, fl_y, fl_z] = sph2cart(-30*pi/180, 0, radius);
    
    switch n_spkrs
        case 5
            S = ambi_spkr_array(...
                ... % array name
                'itu50', ...
                ... % coordinate codes, unit codes
                ... % Azimuth, Elevation, Radius; Degrees, Degrees, Meters
                'AER', 'DDM', ...
                ... % speaker name, [azimuth, elevation, radius]
                'BL', [ 110, 0, radius], ...
                'FL', [  30, 0, radius], ...
                'FC', [   0, 0, fl_x], ...
                'FR', [ -30, 0, radius], ...
                'BR', [-110, 0, radius] ...
                );
        case 7
            S = ambi_spkr_array(...
                ... % array name
                'itu50', ...
                ... % coordinate codes, unit codes
                ... % Azimuth, Elevation, Radius; Degrees, Degrees, Meters
                'AER', 'DDM', ...
                ... % speaker name, [azimuth, elevation, radius]
                'BL', [ 110, 0, radius], ...
                'FL', [  30, 0, radius], ...
                'FC', [   0, 0, fl_x], ...
                'FR', [ -30, 0, radius], ...
                'BR', [-110, 0, radius] ...
                );
    end
    ambi_run_allrad(S, [2,0], [0,0,1; 0,0,-1]);
end
