function [ ] = run_dec_BING16(  )
    %UNTITLED3 Summary of this function goes here
    %   Detailed explanation goes here
    
    %% decoder specs
    decoder_type = 'allrad'; % pinv | allrad
    
    h_order_range = 5;
    v_order_range = 0;
    
    mixed_order_scheme = 'HP';
    
    %% speaker array definition
    % azimuth of speaker at front,
    % change to -45/2 for L/R config
    a0 = 0;
    az = linspace(0,360,17) + a0;
    az = az(1:end-1);
    
    % radius
    r = zeros(size(az))+4;    % meters
    
    % elevations
    el = zeros(size(az));
    
    S = ambi_spkr_array(...
        ... % array name
        'BING16H', ...
        ... % coordinate codes, unit codes
        'AER', 'DDM', ...
        ... % speaker name, [azimuth, radius, elevation]
        ... %
        'S01', [ az(1), el(1), r(1) ], ...
        'S02', [ az(2), el(2), r(2) ], ...
        'S03', [ az(3), el(3), r(3) ], ...
        'S04', [ az(4), el(4), r(4) ], ...
        'S05', [ az(5), el(5), r(5) ], ...
        'S06', [ az(6), el(6), r(6) ], ...
        'S07', [ az(7), el(7), r(7) ], ...
        'S08', [ az(8), el(8), r(8) ], ...
        'S09', [ az(9), el(9), r(9) ], ...
        'S10', [ az(10), el(10), r(10) ], ...
        'S11', [ az(11), el(11), r(11) ], ...
        'S12', [ az(12), el(12), r(12) ], ...
        'S13', [ az(13), el(13), r(13) ], ...
        'S14', [ az(14), el(14), r(14) ], ...
        'S15', [ az(15), el(15), r(15) ], ...
        'S16', [ az(16), el(16), r(16) ] ...
        );
    
    ambi_run_pinv_ambdec_BING16hack(S,[5,0],[],[],false,'HP');
        
end

