function [ S ] = SPKR_ARRAY_BBC16( r, h )
    %UNTITLED Summary of this function goes here
    %   Detailed explanation goes here
    
    %% defaults
    if ~exist('r','var'), r = 1; end
    if ~exist('h','var'), h = sqrt(1/2); end

    %%
    S = ambi_spkr_array(...
        'BBC16', ...
        'ARZ', 'DMM', ...
        'T1', [  45, r,  h ], ...
        'T2', [ 135, r,  h ], ...
        'T3', [ 225, r,  h ], ...
        'T4', [ 315, r,  h ], ...
        'M1', [   0, r,  0 ], ...
        'M2', [  45, r,  0 ], ...
        'M3', [  90, r,  0 ], ...
        'M4', [ 135, r,  0 ], ...
        'M5', [ 180, r,  0 ], ...
        'M6', [ 225, r,  0 ], ...
        'M7', [ 270, r,  0 ], ...
        'M8', [ 315, r,  0 ], ...
        'B1', [  45, r, -h ], ...
        'B2', [ 135, r, -h ], ...
        'B3', [ 225, r, -h ], ...
        'B4', [ 315, r, -h ]  ...
        );
end

