function S = SPKR_ARRAY_CMAP8(array_type, r)
    
    %% defaults
    
    if ~exist('array_type', 'var') || isempty(array_type)
        array_type = 'all';
    end
    
    % radius
    if ~exist('r','var') || isempty(r), r = 2; end   % meters
    
    az_offset = 22.5;
    azis = (0:45:315)+az_offset;
    
    switch lower(array_type)
        case {'all', 'full'}
            S = ambi_spkr_array(...
                ... % array name
                'CMAP8_all', ...
                ... % coordindate codes, unit codes
                'AER', 'DDM', ...
                ... % speaker name, [azimuth, radius, elevation]
                'S1',  [azis(1), 0, r ], ...
                'S2',  [azis(2), 0, r ], ...
                'S3',  [azis(3), 0, r ], ...
                'S4',  [azis(4), 0, r ], ...
                ...
                'S5',  [azis(5), 0, r ], ...
                'S6',  [azis(6), 0, r ], ...
                'S7',  [azis(7), 0, r ], ...
                'S8',  [azis(8), 0, r ] ...
                );
        case 'odd'
            S = ambi_spkr_array(...
                ... % array name
                'CMAP8_odd', ...
                ... % coordindate codes, unit codes
                'AER', 'DDM', ...
                ... % speaker name, [azimuth, radius, elevation]
                'S1',  [azis(1), 0, r ], ...
                ... %'S2',  [azis(2), 0, r ], ...
                'S3',  [azis(3), 0, r ], ...
                ... %'S4',  [azis(4), 0, r ], ...
                ...
                'S5',  [azis(5), 0, r ], ...
                ... %'S6',  [azis(6), 0, r ], ...
                'S7',  [azis(7), 0, r ] ...
                ... %'S8',  [azis(8), 0, r ] ...
                );
        case 'even'
            S = ambi_spkr_array(...
                ... % array name
                'CMAP8_even', ...
                ... % coordindate codes, unit codes
                'AER', 'DDM', ...
                ... % speaker name, [azimuth, radius, elevation]
                ... %'S1',  [azis(1), 0, r ], ...
                'S2',  [azis(2), 0, r ], ...
                ... %'S3',  [azis(3), 0, r ], ...
                'S4',  [azis(4), 0, r ], ...
                ...
                ... %'S5',  [azis(5), 0, r ], ...
                'S6',  [azis(6), 0, r ], ...
                ... %'S7',  [azis(7), 0, r ], ...
                'S8',  [azis(8), 0, r ] ...
                );
    end
    
