function [ val ] = SPKR_ARRAY_BING_2013JAN29( )
    %UNTITLED Summary of this function goes here
    %   Detailed explanation goes here
    
% From: 	Fernando Lopez-Lezcano <nando@ccrma.stanford.edu>
% Subject: 	Re: pesky coefficients...
% Date: 	January 29, 2013 9:16:15 PM PST
%
% #x is the speaker number, second column is the azimuth in degrees and
% column #7 is the elevation in degrees. The others are distance
% measurements. As you can see this is far from regular (for practical
% reasons).
% 
% For the "Floor" speakers you should consider for the decoder that
% elevation is actually 0 for all speakers and ignore the numbers there
% (for speakers #1 to #10). The audience is not in a plane so this does not
% even reflect reality (furthermore the sweet spot is - for this set of
% numbers - elevated with respect to the audience in the first tier of
% seating, we'll see what happens).
% 
% For the rigged speakers (hanging from the ceiling and on the side
% catwalks) use both azimuth and elevation. The "70" elevation for the
% center top cluster is a bit unrealistic I think, probably will be closer
% to 60 - I did not finish with my calculations today.
% 
% All numbers are generated by trying to measure distances and heights in
% my dxf plans of the hall. They should be close to reality but we'll see
% what happens on install day... I'm attaching pdfs of the two sets of
% speakers as seem from the top.

% == Floor:
% 
%     deg  ink    "(d)   "(h)   "(href)  elev(deg)
% 
% #1   10   5.10   1272   256    52       2.3
% #2   -10                                2.3
% #3   32   4.26   1062   399    195      10.4
% #4   -32                                10.4
% #5   76   2.98   743    399    195      14.7
% #6   -76                                14.7
% #7   126  2.66   663    258    54       4.65
% #8   -126                               4.65
% #9   161  2.53   630    339    135      12.09
% #10  -161                               12.09
% 
% == Rigged
% 
%     deg  ink    "(d)   "(h)   "(href)  elev(deg)
%                                                 stage    real
% 
% #11  12   3.30   822           689      40       893
% #12  -12                                40
% #13  27   3.73   929    605(f) 401(f)   23
% #14  -27                                23
% #15  73   2.38   593    605(f) 401(f)   34
% #16  -73                                34
% #17  126  1.51   376           315      40       519
% #18  -126                               40
% #19  161  2.21   551           462      40       666
% #20  -161                               40
% #21  36   1.23   306           840      70       1044
% #22  -36                                70
% #23  119  0.83   249           684      70       888
% #24  -119                               70



    R = 5.0;
    S = [ ...
        % == Floor:
         10	0 R
        -10	0 R
         32	0 R
        -32	0 R
         76	0 R
        -76	0 R
        126	0 R
       -126	0 R
        161	0 R
       -161	0 R
        ...
        % == Rigged
         12 40 R
        -12 40 R
         27 23 R
        -27 23 R
         73 34 R
        -73 34 R
         126 40 R
        -126 40 R
         161 40 R 
        -161 40 R
         36  70 R 
        -36  70 R
         119 70 R 
        -119 70 R
        ];
    
    val.az = S(:,1)*pi/180;
    val.el = S(:,2)*pi/180;
    [val.x, val.y, val.z] = sph2cart(val.az, val.el, 1);
    val.r = S(:,3);
    val.id = {
        'F01', 'F02', 'F03', 'F04', 'F05', 'F06', 'F07', 'F08', ...
        'R09', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15', 'R16', ...
        'R17', 'R18', 'R19', 'R20', 'R21', 'R22', 'R23', 'R24' ...
        };
    val.name = 'BING_2013JAN29';
    
end

